/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;
import java.awt.Image;
import java.io.File;
import javax.imageio.ImageIO;
import java.awt.image.BufferedImage;
import java.util.regex.*;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;

import javax.swing.JOptionPane;

/**
 *
 * @author NAMITHA SHREE
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    private File selectedImageFile;
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        Jpanel = new javax.swing.JPanel();
        CusterInformationLable = new javax.swing.JLabel();
        FirstNameLabel = new javax.swing.JLabel();
        LastNameLabel = new javax.swing.JLabel();
        AgeLabel = new javax.swing.JLabel();
        EmailLabel = new javax.swing.JLabel();
        FirstNameText = new javax.swing.JTextField();
        LastNameText = new javax.swing.JTextField();
        AgeText = new javax.swing.JTextField();
        EmailText = new javax.swing.JTextField();
        MessageLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        MessageArea = new javax.swing.JTextArea();
        SubmitButton = new javax.swing.JButton();
        PhotoLabel = new javax.swing.JLabel();
        FirstNameError = new javax.swing.JLabel();
        LastNameError = new javax.swing.JLabel();
        AgeError = new javax.swing.JLabel();
        EmailError = new javax.swing.JLabel();
        UploadButton = new javax.swing.JButton();
        PathLabel = new javax.swing.JLabel();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Jpanel.setBackground(new java.awt.Color(204, 255, 153));

        CusterInformationLable.setBackground(new java.awt.Color(255, 51, 204));
        CusterInformationLable.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        CusterInformationLable.setText("Customer Registration Form");

        FirstNameLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        FirstNameLabel.setText("First Name:");

        LastNameLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        LastNameLabel.setText("Last Name:");

        AgeLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        AgeLabel.setText("Age:");

        EmailLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        EmailLabel.setText("Email:");

        FirstNameText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                FirstNameTextKeyReleased(evt);
            }
        });

        LastNameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LastNameTextActionPerformed(evt);
            }
        });
        LastNameText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                LastNameTextKeyReleased(evt);
            }
        });

        AgeText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgeTextActionPerformed(evt);
            }
        });
        AgeText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                AgeTextKeyReleased(evt);
            }
        });

        EmailText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                EmailTextKeyReleased(evt);
            }
        });

        MessageLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        MessageLabel.setText("Message:");

        MessageArea.setColumns(20);
        MessageArea.setRows(5);
        jScrollPane1.setViewportView(MessageArea);

        SubmitButton.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        SubmitButton.setText("SUBMIT");
        SubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitButtonActionPerformed(evt);
            }
        });

        PhotoLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        PhotoLabel.setText("Photo:");

        FirstNameError.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        FirstNameError.setForeground(new java.awt.Color(255, 51, 51));

        LastNameError.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        LastNameError.setForeground(new java.awt.Color(255, 0, 51));

        AgeError.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        AgeError.setForeground(new java.awt.Color(255, 0, 51));

        EmailError.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        EmailError.setForeground(new java.awt.Color(255, 51, 51));

        UploadButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        UploadButton.setText("Upload Photo");
        UploadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UploadButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JpanelLayout = new javax.swing.GroupLayout(Jpanel);
        Jpanel.setLayout(JpanelLayout);
        JpanelLayout.setHorizontalGroup(
            JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpanelLayout.createSequentialGroup()
                .addGroup(JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JpanelLayout.createSequentialGroup()
                        .addGap(201, 201, 201)
                        .addComponent(CusterInformationLable))
                    .addGroup(JpanelLayout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addGroup(JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LastNameLabel)
                            .addComponent(FirstNameLabel)
                            .addComponent(AgeLabel)
                            .addComponent(EmailLabel)
                            .addComponent(MessageLabel)
                            .addComponent(PhotoLabel))
                        .addGap(124, 124, 124)
                        .addGroup(JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JpanelLayout.createSequentialGroup()
                                .addGroup(JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(EmailText, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(LastNameText, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                                            .addComponent(FirstNameText, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addComponent(AgeText, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(FirstNameError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(JpanelLayout.createSequentialGroup()
                                        .addGroup(JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(LastNameError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(AgeError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(EmailError, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(JpanelLayout.createSequentialGroup()
                                .addGroup(JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(JpanelLayout.createSequentialGroup()
                                        .addComponent(UploadButton)
                                        .addGap(34, 34, 34)
                                        .addComponent(PathLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 18, Short.MAX_VALUE))))
                    .addGroup(JpanelLayout.createSequentialGroup()
                        .addGap(287, 287, 287)
                        .addComponent(SubmitButton)))
                .addContainerGap())
        );
        JpanelLayout.setVerticalGroup(
            JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(CusterInformationLable)
                .addGap(27, 27, 27)
                .addGroup(JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FirstNameLabel)
                    .addComponent(FirstNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FirstNameError, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LastNameLabel)
                    .addComponent(LastNameText, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LastNameError, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JpanelLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(AgeLabel))
                    .addGroup(JpanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AgeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AgeError))))
                .addGap(25, 25, 25)
                .addGroup(JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EmailLabel)
                    .addComponent(EmailText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EmailError))
                .addGap(29, 29, 29)
                .addGroup(JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MessageLabel)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PhotoLabel)
                    .addComponent(UploadButton)
                    .addComponent(PathLabel))
                .addGap(75, 75, 75)
                .addComponent(SubmitButton)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Jpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Jpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LastNameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LastNameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LastNameTextActionPerformed

    private void AgeTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgeTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AgeTextActionPerformed

    private void SubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitButtonActionPerformed
      String firstname=FirstNameText.getText();
      String lastname=LastNameText.getText();
      String age=AgeText.getText();
      String email=EmailText.getText();
      String message=MessageArea.getText();
     if (firstname.equals("") || lastname.equals("") || age.equals("") || email.equals("")) {
           JOptionPane.showMessageDialog(null, "All the fields are mandatory");
       } else {
           if (selectedImageFile != null) {
               try {
                   BufferedImage img = ImageIO.read(selectedImageFile);
                   ImageIcon icon = new ImageIcon(img);
                   JOptionPane.showMessageDialog(this,
                           "CUSTOMER FIRST NAME: " + firstname + "\n" +
                                   "CUSTOMER LAST NAME: " + lastname + "\n" +
                                   "CUSTOMER AGE: " + age + "\n" +
                                   "CUSTOMER EMAIL ID: " + email + "\n" +
                                   "MESSAGE: " + message,
                           "CUSTOMER DETAILS", JOptionPane.INFORMATION_MESSAGE, icon);
               } catch (Exception ex) {
                   JOptionPane.showMessageDialog(this, "Error loading the image.", "Error", JOptionPane.ERROR_MESSAGE);
               }
           } else {
               JOptionPane.showMessageDialog(this, "Please upload a photo before submitting.", "Error", JOptionPane.ERROR_MESSAGE);
           }
     }
    }//GEN-LAST:event_SubmitButtonActionPerformed

    private void FirstNameTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FirstNameTextKeyReleased
        String PATTERN="^[a-zA-Z]{0,30}$";
        Pattern patt=Pattern.compile(PATTERN);
        Matcher match =patt.matcher(FirstNameText.getText());
        if(!match.matches()){
            FirstNameError.setText("Enter only Alphabets");
        }else{
             FirstNameError.setText("");
        }
        
    }//GEN-LAST:event_FirstNameTextKeyReleased

    private void LastNameTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LastNameTextKeyReleased
        String PATTERN="^[a-zA-Z]{0,30}$";
        Pattern patt=Pattern.compile(PATTERN);
        Matcher match =patt.matcher(LastNameText.getText());
        if(!match.matches()){
            LastNameError.setText("Enter only Alphabets");
        }else{
             LastNameError.setText("");
        }
    }//GEN-LAST:event_LastNameTextKeyReleased

    private void AgeTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AgeTextKeyReleased
        String PATTERN="^[0-9]{0,3}$";
        Pattern patt=Pattern.compile(PATTERN);
        Matcher match =patt.matcher(AgeText.getText());
        if(!match.matches()){
            AgeError.setText("Enter only Numbers");
        }else{
             AgeError.setText("");
        }
    }//GEN-LAST:event_AgeTextKeyReleased

    private void EmailTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EmailTextKeyReleased
        String PATTERN="^[a-zA-Z0-9]{0,30}[@][a-zA-Z0-9]{0,10}[.][a-zA-Z]{0,5}$";
        Pattern patt=Pattern.compile(PATTERN);
        Matcher match =patt.matcher(EmailText.getText());
        if(!match.matches()){
            EmailError.setText("Enter valid EmailID");
        }
        else{
             EmailError.setText("");
        }
    }//GEN-LAST:event_EmailTextKeyReleased

    private void UploadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UploadButtonActionPerformed
                                                   
      // JFileChooser fileChooser = new JFileChooser();
       JFileChooser chooser=new JFileChooser();
       //chooser.showOpenDialog(null);
       int returnValue = chooser.showOpenDialog(null);
       if (returnValue == JFileChooser.APPROVE_OPTION) {
           selectedImageFile = chooser.getSelectedFile();
          
           try {  
               BufferedImage img = ImageIO.read(selectedImageFile);
               ImageIcon icon = new ImageIcon(img);
               String filename=null;
               filename = selectedImageFile.getAbsolutePath();
               PathLabel.setText(filename);
       
           } catch (Exception ex) {
               JOptionPane.showMessageDialog(this, "Error", "Error", JOptionPane.ERROR_MESSAGE);
           }
       
    }
    }//GEN-LAST:event_UploadButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AgeError;
    private javax.swing.JLabel AgeLabel;
    private javax.swing.JTextField AgeText;
    private javax.swing.JLabel CusterInformationLable;
    private javax.swing.JLabel EmailError;
    private javax.swing.JLabel EmailLabel;
    private javax.swing.JTextField EmailText;
    private javax.swing.JLabel FirstNameError;
    private javax.swing.JLabel FirstNameLabel;
    private javax.swing.JTextField FirstNameText;
    private javax.swing.JPanel Jpanel;
    private javax.swing.JLabel LastNameError;
    private javax.swing.JLabel LastNameLabel;
    private javax.swing.JTextField LastNameText;
    private javax.swing.JTextArea MessageArea;
    private javax.swing.JLabel MessageLabel;
    private javax.swing.JLabel PathLabel;
    private javax.swing.JLabel PhotoLabel;
    private javax.swing.JButton SubmitButton;
    private javax.swing.JButton UploadButton;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
